spring.application.name=raastqr
server.port=3000
app.bank-url=http://localhost:8080/pacs008
app.sbp-status-url=http://localhost:8080/pacs002/messages
app.send-on-startup=true
app.sbp-poll.fixed-delay-ms=10000
app.sbp-poll.initial-delay-ms=10000


