spring.application.name=raastqr
server.port=3000
app.bank-url=http://localhost:8080/pacs008
app.sbp-status-url=http://localhost:8080/pacs002/messages
app.send-on-startup=true
app.sbp-poll.fixed-delay-ms=10000
app.sbp-poll.initial-delay-ms=10000



spring.datasource.url=jdbc:postgresql://localhost:9090/raast
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
